on: [push, pull_request]

defaults:
    run:
        shell: bash

env:
    APT: sudo apt install -y --no-install-recommends

jobs:
    cpp_octave:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: $APT cppcheck
            - run: $APT python3-pip python3-setuptools
            - run: sudo pip3 install scspell3k
            - run: $APT libboost-all-dev libeigen3-dev octave liboctave-dev
            - run: $APT clang-tidy-9
            - run: make test

    dependency:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - run: $APT libeigen3-dev
            - run: make build
            - run: sudo make install
            - run: make test_dependency

    bionic_melodic_catkin_old:
        container: ros:melodic-ros-base-bionic
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                source /opt/ros/melodic/setup.bash
                make catkin_test_old ROS_DISTRO=melodic UBUNTU_DISTRO=bionic

    bionic_melodic_catkin_new:
        container: ros:melodic-ros-base-bionic
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                source /opt/ros/melodic/setup.bash
                make catkin_test_new ROS_DISTRO=melodic UBUNTU_DISTRO=bionic

    prerelease:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: make ros_prerelease ROS_DISTRO=melodic UBUNTU_DISTRO=bionic BRANCH=`git branch --show-current`
              env:
                  CCACHE_DIR: ${GITHUB_WORKSPACE}/.ccache


    bionic_scanbuild:
        runs-on: ubuntu-18.04

        # Install system dependencies, namely a very barebones ROS setup.
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt update
            - run: $APT libboost-all-dev libeigen3-dev octave liboctave-dev
            - run: $APT clang-tidy-9
            - run: make clangcheck SCANBUILD=scan-build-9

